### ISSUE TITLE
RxValidator  defineValidator

### ISSUE THREAD

**Issue by 530l** [fengzhizi715/kvalidation#1]
defineRxValidator(password) { defineValidator<String> { this addRule MinLengthRule(1) } }
        .toObservable(error = { println(it) })
        .subscribe { println(it) }  这种写法不行吗

**Comment by fengzhizi715** [comment]
defineRxValidator(data: T, block: RxValidator<T>.() -> Unit) 是这样定义的，block 是一个 RxValidator<T>.() -> Unit 类型。而 defineValidator(block: Validator<T>.() -> Unit) 返回的是 Validator<T> 类型。

RxValidator 是Validator的子类，Validator 并不能转化成 RxValidator。所以，上述写法不行。

**Comment by 530l** [comment]
RxValidator 能组合多个条件吗

**Comment by fengzhizi715** [comment]
@linyingfa 可以的。例如：

    val password = "123456a"

    defineRxValidator(password) {
        this addRule MinLengthRule(6)                                       // 密码长度不能小于6位

        this addRule PatternRule("^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]+$") // 密码必须数字和字母的组合
    }
